[package]
name = "leitner_box_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catppuccin-egui = "3.1.0"
eframe = "0.22.0"
env_logger = "0.10.0"
image = "0.24.7"
